on:
  push:
    tags:
      - "v*"
name: Build and Upload Releases
jobs:
  build:
    name: Build and Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.13.1
      - name: Build project
        run: |
          go run tools/prebuildstep.go
          GOOS=darwin GOARCH=amd64 go build -o gocaves-macos
          GOOS=linux GOARCH=amd64 go build -o gocaves-linux
          GOOS=windows GOARCH=amd64 go build -o gocaves-windows.exe
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          tag_name: "${{ github.ref }}"
          release_name: "Release ${{ github.ref }}"
          draft: false
          prerelease: false
      - name: Upload Linux Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          upload_url: "${{ steps.create_release.outputs.upload_url }}"
          asset_path: ./gocaves-linux
          asset_name: gocaves-linux
          asset_content_type: application/octet-stream
      - name: Upload OSX Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          upload_url: "${{ steps.create_release.outputs.upload_url }}"
          asset_path: ./gocaves-macos
          asset_name: gocaves-macos
          asset_content_type: application/octet-stream
      - name: Upload Windows Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          upload_url: "${{ steps.create_release.outputs.upload_url }}"
          asset_path: ./gocaves-windows.exe
          asset_name: gocaves-windows.exe
          asset_content_type: application/octet-stream
